linters:
  enable:
    - godox
    - misspell
    - revive

linters-settings:
  revive:
    ignore-generated-header: true
    severity: warning
    rules:
      - name: exported

issues:
  exclude-use-default: false
